---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myproject
  namespace: argocd
spec:
  description: myproject
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: test-role1234
      description: test role, waiting for a Terraform ArgoCD provider resource
      policies:
        - p, proj:myproject:test-role1234, applications, override, myproject/*, allow
        - p, proj:myproject:test-role1234, applications, sync, myproject/*, allow
        - p, proj:myproject:test-role1234, applications, update, myproject/*, allow
        - p, proj:myproject:test-role1234, applications, get, myproject/*, allow
